from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from langchain_core.messages import AIMessage
import os

# Import the LangGraph agent
from Agent1 import app as ai_app

app = FastAPI()

# Pydantic model for receiving data from the frontend
class ChatRequest(BaseModel):
    message: str
    thread_id: str

@app.get("/", response_class=HTMLResponse)
async def read_index():
    # Read and return the HTML file directly
    with open("index.html", "r", encoding="utf-8") as file:
        return file.read()

@app.post("/chat")
async def chat_endpoint(request: ChatRequest):
    # Pass the user message
    initial_input = {'messages': [("user", request.message)]}
    thread_data = {'configurable': {'thread_id': request.thread_id}}
    
    ai_response = ""
    
    # Run the LangGraph agent asynchronously
    async for event in ai_app.astream(initial_input, thread_data, stream_mode='values'):
        messages = event.get('messages', [])
        if not messages:
            continue
            
        last_message = messages[-1]
        
        # We ONLY want to capture the final message generated by the AI
        if isinstance(last_message, AIMessage):
            # If the AI sent actual content (and not just a hidden tool call)
            if last_message.content:
                
                # If Gemini returns a list of blocks, extract the text
                if isinstance(last_message.content, list):
                    text_parts = []
                    for block in last_message.content:
                        if isinstance(block, dict) and "text" in block:
                            text_parts.append(block["text"])
                        elif isinstance(block, str):
                            text_parts.append(block)
                    ai_response = "\n".join(text_parts)
                    
                # If Gemini returns a normal string
                else:
                    ai_response = str(last_message.content)
                    
    return {"response": ai_response}